### ISSUE TITLE
Consider adding Digital Asset RPC API Infrastructure to SeaORM showcase!

### ISSUE THREAD

**Issue by billy1624** [metaplex-foundation/digital-asset-rpc-infrastructure#1]
Hey Metaplex team, feel free to submit a PR to showcase your project!
- https://github.com/SeaQL/sea-orm/issues/403

**Comment by staccDOTsol** [comment]
Thanks for bringing this to my attention! It looks like the SeaORM team is suggesting that the Metaplex team submit a pull request to add Digital Asset RPC API Infrastructure to the SeaORM showcase. This is a great opportunity to showcase the capabilities of Metaplex and its integration with SeaORM. 

To get started, you can follow these steps:

1. Fork the SeaORM repository to your own GitHub account.
2. Clone the forked repository to your local machine.
3. Create a new branch for your changes.
4. Add the Digital Asset RPC API Infrastructure to the showcase.
5. Commit your changes and push them to your forked repository.
6. Submit a pull request to the SeaORM repository.

Make sure to follow the SeaORM contribution guidelines and provide a clear description of your changes in the pull request. Good luck!

**Comment by danenbm** [comment]
I think we will skip that as we don't really have time at the moment, although it looks cool an interesting!
