### ISSUE TITLE
Outdated init.sql

### ISSUE THREAD

**Issue by mohsen-vybenetwork** [metaplex-foundation/digital-asset-rpc-infrastructure#115]
I have encountered several errors regarding missing columns in the following tables: asset, asset_creators, and asset_grouping. These missing columns are causing issues in the application.

Here is a list of the missing columns in the asset table:

    data_hash
    creator_hash
    owner_delegate_seq
    was_decompressed
    leaf_seq

Additionally, there are issues with the following columns in the other tables:

    asset_creators.position
    asset_grouping.verified

Thank you for your attention to this matter.

**Comment by linuskendall** [comment]
Did you run migrations after init.sql?

**Comment by mohsen-vybenetwork** [comment]
All good now after using the migration tool.
