### ISSUE TITLE
Regular NFTs not showing up in DAS API

### ISSUE THREAD

**Issue by ethyi** [metaplex-foundation/digital-asset-rpc-infrastructure#49]
Regular NFTs are not showing up in the DAS API. Helius Labs is actively investigating

Current Findings: 
- NFT onchain and offchain data is indexed properly in primary and replica DB
- NFTs that couldn't be queried by the API yesterday seem to appear today. 

Example of a previous failure (now successful)
- D1APVxjAiDwzFsPfhLbVyAC2xPyTaeAcCdGd2HYWfLjg

Examples of failures (as of writing)
-CnpYvDnvvWZtWbYMxP38wGPh1jY3rqvbKMS8R5ActZAG

**Comment by linuskendall** [comment]
Some of these may be affected by #44
